site_name: FunnyStocks Development Process
docs_dir: "markdown"
site_dir: "docs"
site_description: "Documentation of building a stock market game in GCP free tier compute instance."
site_author: "funnyStocks"
repo_url: "https://github.com/funnystocks/docs"
repo_name: "GitHub"
nav:
  - Home: "index.md"
  - Introduction: "intro.md"
  - Getting Started:
    - Installation: "getting-started/installation.md"
    - Quickstart: "getting-started/quickstart.md"
  - User Guide:
    - Overview: "user-guide/overview.md"
    - Configuration: "user-guide/configuration.md"
  - API Reference: "api.md"
  - Contributing: "contributing.md"
theme:
  name: "readthedocs"
  language: en

  # THIS IS AI-GENERATED VIA GOOGLE GEMINI, NOT MY OWN CODE.
