site_name: FunnyStocks
docs_dir: "markdown"
site_dir: "docs"
site_description: "Documentation of building a stock market game in GCP free tier compute instance."
site_author: "funnyStocks"
repo_url: "https://github.com/funnystocks/docs"
repo_name: "GitHub"
nav:
  - Home: "markdown/index.md"
theme:
  name: "readthedocs"
  language: en

  # THIS IS AI-GENERATED VIA GOOGLE GEMINI, NOT MY OWN CODE.
